name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Tipo de release (major, minor, patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Necesario para crear tags/releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Bump version
        id: bump
        run: |
          version="${latest_tag#v}"
          major=$(echo $version | cut -d. -f1)
          minor=$(echo $version | cut -d. -f2)
          patch=$(echo $version | cut -d. -f3)

          case "${{ github.event.inputs.release_type }}" in
            major)
              major=$((major+1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor+1))
              patch=0
              ;;
            patch)
              patch=$((patch+1))
              ;;
          esac

          new_version="v$major.$minor.$patch"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Create Release
        run: |
          gh release create "$new_version" \
            --title "$new_version" \
            --notes "Release $new_version generado manualmente"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}